[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm run docs:build"

[[redirects]]
  from = "/chat"
  to = "https://discord.gg/Xta6huNhVv"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

